@startuml

cloud DataBase_System #LightBlue[
**Database System (Cloud server)**
Central system with the main goal
to gather all the data (working hours)
From all clients
]

component Timelink_mobile #B7C9E2[
    **Timelink mobile**

    Mobile application component
    
    Simple application where all employees can
    manage their working hours.
]

component Timelink_admin #536878;text:White;line:White[
    **Timelink admin**

    Administrator web application allowing to manage
    users, working places and working hours.
]

DataBase_System -- Timelink_admin

DataBase_System -- Timelink_mobile

@enduml